apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: authservice
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: authservice
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:4002
            - name: ConnectionStrings__DefaultConnection
              value: Server=auth-db;Port=5433;Database=kwetter.AuthService;User Id=postgres;Password=postgres;
            - name: RabbitMQConnectionString
              value: amqp://username:password@rabbitmq:5672
          image: docker.io/martijnweber/authservice
          name: authservice
          ports:
            - containerPort: 4002
          resources: {}
      hostname: authservice
      restartPolicy: Always
status: {}
